In [21]:
import numpy as np
import random as random
#using simpleguitk for display, is not needed for computer game
import simpleguitk as simplegui
import time
#new ones
import pandas as pd
from xgboost import XGBRegressor
import os

In [22]:
myPath='/home/tobias/ml-testing/games/skyjo'
length=len([f for f in os.listdir(myPath) 
    if f.startswith('human_computer1_') and os.path.isfile(os.path.join(myPath, f))])

In [23]:
res=np.zeros((7,length))
deltahuman=0
deltacomputer=0
for i in range(length):
    if i<9:
        file=np.loadtxt('human_computer1_00'+str(i+1)+'.txt')
    elif i>=9 and i<99:
        file=np.loadtxt('human_computer1_0'+str(i+1)+'.txt')    
    res[0,i]=i+1
    #number of turns is overall not set zero for new game from game 50 correct
    res[4,i]=file.shape[1]
    #start player #does not change in new game also from game 50 correct
    res[5,i]=file[0,0]
    #last player
    res[6,i]=file[0,file.shape[1]-1]
    #always player 0, human first 
    if file[0,0]==0:
        res[1:3,i]=file[49:51,0]
    else:
        res[1,i]=file[50,0]
        res[2,i]=file[49,0]
    if res[1,i]<res[2,i]:
        #human winner mark
        res[3,i]=1
        deltahuman+=(res[2,i]-res[1,i])
    else:
        deltacomputer+=(res[1,i]-res[2,i])
print(res.T)        

[[  1.  24.  46.   1.  30.   0.   1.]
 [  2.  36.   9.   0.  32.   0.   1.]
 [  3.  78.  24.   0.  31.   1.   1.]
 [  4.  11.  49.   1.  24.   0.   1.]
 [  5.   9.  22.   1.  26.   0.   1.]
 [  6.  13.  28.   1.  78.   1.   1.]
 [  7.   9.  19.   1.  41.   1.   1.]
 [  8.  10.  30.   1.  33.   1.   1.]
 [  9.  32.   8.   0.  31.   1.   1.]
 [ 10.  20.  24.   1.  41.   1.   1.]
 [ 11.  22.  34.   1.  34.   0.   1.]
 [ 12.  17.  41.   1.  34.   0.   1.]
 [ 13.  27.  29.   1.  61.   0.   1.]
 [ 14.  46.  15.   0.  92.   0.   1.]
 [ 15.  11.  23.   1.  32.   0.   1.]
 [ 16.  12.  36.   1.  56.   0.   1.]
 [ 17.  16.  22.   1.  35.   1.   1.]
 [ 18.  36.   4.   0.  71.   1.   1.]
 [ 19.  19.  28.   1.  95.   1.   1.]
 [ 20.  18.  32.   1. 131.   1.   1.]
 [ 21.  26.  13.   0. 167.   1.   1.]
 [ 22.  10.  55.   1. 194.   1.   1.]
 [ 23.  28.  41.   1. 230.   1.   1.]
 [ 24.  20.  65.   1. 254.   1.   1.]
 [ 25.  29.  39.   1. 280.   1.   1.]
 [ 26.  35.  45.   1. 308.   1.   1.]
 [ 27.  24. 

In [26]:
print(sum(res[3]), res.shape[1])

print(f"human average {round(np.mean(res[1]),3)} points")
                       
print(f"computer average {round(np.mean(res[2]),3)} points")
print(f"human adventage of  {round(np.mean(res[2]-res[1]),3)} points")
print(f"human wins to {round(np.mean(res[3]*100),1)} %")

42.0 53
human average 24.66
computer average 32.34
human adventage of  7.679
human wins to 79.2 %


In [13]:
#average win is by to be determine deltapoints
print(f"human average adventage {round(deltahuman/sum(res[3]),3)} points")
print(f"computer average adventage {round(deltacomputer/(res.shape[1]-sum(res[3])),3)} points")

human average adventage 17.361 points
computer average adventage 32.3 points


(51, 145)
