In [5]:
#should suppress warnings
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

import numpy as np
import random as random
import scipy
#using simpleguitk for display, is not needed for computer game
import simpleguitk as simplegui
import time
#new ones
import pandas as pd
from xgboost import XGBRegressor
import os
#skyjo game classes and functions
from skyjo_functions4 import *
#own functions for machine learning
from ml_functions2 import *
#for plotting 
from matplotlib import pyplot as plt
from matplotlib.pyplot import figure

The different computer levels against each other. Testing the newest level 9 and then 11, first against the random level 0. 

Then again level 5 which seems to be the best previous level (or level 1 but both are rather similar anyway). Since level 5 gets sometime sin an infinite loope, level 6 is used instead. 

In [7]:
 

names=('alpha','beta')
nature=('computer','computer')
levels=(11,6)
start_time=time.time()
nn=int(500)
all_scores=np.zeros((7,nn))
for i in range(nn):
    print(f"running case {i}")
    scores,turns,last_player,output=skyjo_round(names,nature,levels,0,True,True,True)
    all_scores[0,i]=i
    all_scores[1:3,i]=scores
    all_scores[3,i]=turns
    all_scores[4,i]=np.argmin(scores)
    all_scores[5,i]=output[0,0]
    all_scores[6,i]=output[0,output.shape[1]-1]    
stop_time=time.time()
print(f"running time was {stop_time-start_time}")
print(all_scores.T)
np.savetxt("level11_level6_500_0.txt",all_scores)

running case 0
running case 1
running case 2
running case 3
running case 4
running case 5
running case 6
running case 7
running case 8
running case 9
running case 10
running case 11
running case 12
running case 13
running case 14
running case 15
running case 16
running case 17
running case 18
running case 19
running case 20
running case 21
running case 22
running case 23
running case 24
running case 25
running case 26
running case 27
running case 28
running case 29
running case 30
running case 31
running case 32
running case 33
running case 34
running case 35
running case 36
running case 37
running case 38
running case 39
running case 40
running case 41
running case 42
running case 43
running case 44
running case 45
running case 46
running case 47
running case 48
running case 49
running case 50
running case 51
running case 52
running case 53
running case 54
running case 55
running case 56
running case 57
running case 58
running case 59
running case 60
running case 61
running case 62
ru

running case 489
running case 490
running case 491
running case 492
running case 493
running case 494
running case 495
running case 496
running case 497
running case 498
running case 499
running time was 439.95981001853943
[[  0.  12.  24. ...   0.   0.   1.]
 [  1.  40.   1. ...   1.   1.   1.]
 [  2.  64.   4. ...   1.   0.   1.]
 ...
 [497.  26.   4. ...   1.   1.   0.]
 [498.  56.  24. ...   1.   1.   1.]
 [499.  15.  16. ...   0.   0.   1.]]


In [15]:
all_scores=np.loadtxt("level9_level0_500_0.txt")
deltalevel9=0
deltalevel0=0
for i in range(all_scores.shape[1]):
    if all_scores[1,i]<all_scores[2,i]:
        #to calculate by how much a  human wins in average 
        deltalevel9+=(all_scores[2,i]-all_scores[1,i])
    else:
        deltalevel0+=(all_scores[1,i]-all_scores[2,i])
print("level 9 gainst level 0")
print(f"level 9 won {int(all_scores.shape[1]-sum(all_scores[4]))} times of {all_scores.shape[1]} rounds")
print(f"the level 9 average is {round(np.mean(all_scores[1]),3)} points")
print(f"the level 0 average is {round(np.mean(all_scores[2]),3)} points")
print(f"the level 9 average adventage is  {round(np.mean(all_scores[2]-all_scores[1]),3)} points")
print(f"level 9 wins to {round(np.mean(100-all_scores[4]*100),1)} %")
print(f"level 9 average adventage {round(deltalevel9/(all_scores.shape[1]-sum(all_scores[4])),3)} points")
print(f"level 0 average adventage {round(deltalevel0/(sum(all_scores[4])),3)} points")


all_scores=np.loadtxt("level11_level0_500_0.txt")
deltalevel9=0
deltalevel0=0
for i in range(all_scores.shape[1]):
    if all_scores[1,i]<all_scores[2,i]:
        #to calculate by how much a  human wins in average 
        deltalevel9+=(all_scores[2,i]-all_scores[1,i])
    else:
        deltalevel0+=(all_scores[1,i]-all_scores[2,i])
print("level 11 gainst level 0")
print(f"level 11 won {int(all_scores.shape[1]-sum(all_scores[4]))} times of {all_scores.shape[1]} rounds")
print(f"the level 11 average is {round(np.mean(all_scores[1]),3)} points")
print(f"the level 0 average is {round(np.mean(all_scores[2]),3)} points")
print(f"the level 11 average adventage is  {round(np.mean(all_scores[2]-all_scores[1]),3)} points")
print(f"level 11 wins to {round(np.mean(100-all_scores[4]*100),1)} %")
print(f"level 11 average adventage {round(deltalevel9/(all_scores.shape[1]-sum(all_scores[4])),3)} is points")
print(f"level 0 average adventage {round(deltalevel0/(sum(all_scores[4])),3)} is points")

level 9 gainst level 0
level 9 won 491 times of 500 rounds
the level 9 average is 28.128 points
the level 0 average is 86.896 points
the level 9 average adventage is  58.768 points
level 9 wins to 98.2 %
level 9 average adventage 60.22 points
level 0 average adventage 20.444 points
level 11 gainst level 0
level 11 won 494 times of 500 rounds
the level 11 average is 20.434 points
the level 0 average is 86.316 points
the level 11 average adventage is  65.882 points
level 11 wins to 98.8 %
level 11 average adventage 67.158 points
level 0 average adventage 39.167 points


Level 9 and level performs very well against level 0. That is ensuring and was not guranteed since it was trained mostly on rather few human data sets. 




In [13]:
all_scores=np.loadtxt("level9_level6_500_0.txt")
deltalevel9=0
deltalevel6=0
for i in range(all_scores.shape[1]):
    if all_scores[1,i]<all_scores[2,i]:
        #to calculate by how much a  human wins in average 
        deltalevel9+=(all_scores[2,i]-all_scores[1,i])
    else:
        deltalevel6+=(all_scores[1,i]-all_scores[2,i])
print("level 9 against level 6")
print(f"level 9 won {int(all_scores.shape[1]-sum(all_scores[4]))} times of {all_scores.shape[1]} rounds")
print(f"the level 9 average is {round(np.mean(all_scores[1]),3)} points")
print(f"the level 6 average is {round(np.mean(all_scores[2]),3)} points")
print(f"the level 9 average adventage is  {round(np.mean(all_scores[2]-all_scores[1]),3)} points")
print(f"level 9 wins to {round(np.mean(100-all_scores[4]*100),1)} %")
print(f"level 9 average adventage {round(deltalevel9/(all_scores.shape[1]-sum(all_scores[4])),3)} points")
print(f"level 6 average adventage {round(deltalevel6/(sum(all_scores[4])),3)} points")


level 9 against level 6
level 9 won 210 times of 500 rounds
the level 9 average is 35.754 points
the level 6 average is 21.344 points
the level 9 average adventage is  -14.41 points
level 9 wins to 42.0 %
level 9 average adventage 11.143 points
level 6 average adventage 32.914 points


In [14]:
all_scores2=np.loadtxt("level11_level6_500_0.txt")
deltalevel11=0
deltalevel6=0
for i in range(all_scores2.shape[1]):
    if all_scores2[1,i]<all_scores2[2,i]:
        #to calculate by how much a  human wins in average 
        deltalevel11+=(all_scores2[2,i]-all_scores2[1,i])
    else:
        deltalevel6+=(all_scores2[1,i]-all_scores2[2,i])
print("level 11 against level 6")
print(f"level 11 won {int(all_scores2.shape[1]-sum(all_scores2[4]))} times of {all_scores2.shape[1]} rounds")
print(f"the level 11 average is {round(np.mean(all_scores2[1]),3)} points")
print(f"the level 6 average is {round(np.mean(all_scores2[2]),3)} points")
print(f"the level 11 average adventage is  {round(np.mean(all_scores2[2]-all_scores2[1]),3)} points")
print(f"level 11 wins to {round(np.mean(100-all_scores2[4]*100),1)} %")
print(f"level 11 average adventage {round(deltalevel11/(all_scores2.shape[1]-sum(all_scores2[4])),3)} points")
print(f"level 6 average adventage {round(deltalevel6/(sum(all_scores2[4])),3)} points")


level 11 against level 6
level 11 won 199 times of 500 rounds
the level 11 average is 37.66 points
the level 6 average is 20.632 points
the level 11 average adventage is  -17.028 points
level 11 wins to 39.8 %
level 11 average adventage 11.774 points
level 6 average adventage 36.07 points


The human imitation level (9) performs somehwat worse, clearer in the points than in the win fraction. 

Level 11 is very similar (numbers too small to be certain), does not seem better. 

In [28]:
#not clear hwther needed, previous results, also should use function
all_scores1=np.loadtxt("level6_level2_1000_0.txt")
all_scores2=np.loadtxt("level6_level2_1000_1.txt")
all_scores3=np.loadtxt("level6_level2_3000_0.txt")
all_scores=np.zeros((7,5000))
all_scores[:,0:1000]=all_scores1
all_scores[:,1000:2000]=all_scores2
all_scores[:,2000:5000]=all_scores3
print(f"to {np.round(np.mean(all_scores[6])*100,3)} % finishes level 2")
deltalevel6=0
deltalevel2=0
for i in range(all_scores.shape[1]):
    if all_scores[1,i]<all_scores[2,i]:
        #to calculate by how much a  human wins in average 
        deltalevel6+=(all_scores[2,i]-all_scores[1,i])
    else:
        deltalevel2+=(all_scores[1,i]-all_scores[2,i])
print("level 6 gainst level 2")
print(f"level 6 won {int(all_scores.shape[1]-sum(all_scores[4]))} times of {all_scores.shape[1]} rounds")
print(f"the level 6 average is {round(np.mean(all_scores[1]),3)} points")
print(f"the level 2 average is {round(np.mean(all_scores[2]),3)} points")
print(f"the level 6 average adventage is  {round(np.mean(all_scores[2]-all_scores[1]),3)} points")
print(f"level 6 wins to {round(np.mean(100-all_scores[4]*100),1)} %")
print(f"level 6 average adventage {round(deltalevel6/(all_scores.shape[1]-sum(all_scores[4])),3)} points")
print(f"level 2 average adventage {round(deltalevel2/(sum(all_scores[4])),3)} points")

to 46.08 % finishes level 2
level 6 gainst level 2
level 6 won 2676 times of 5000 rounds
the level 6 average is 19.235 points
the level 2 average is 23.177 points
the level 6 average adventage is  3.943 points
level 6 wins to 53.5 %
level 6 average adventage 20.796 points
level 2 average adventage 15.464 points


Level 6 is better, now likely robust against noise, but even if it is better it is a small not so relevant adventage.  