In [1]:
import numpy as np
import random as random
import scipy
#using simpleguitk for display, is not needed for computer game
import simpleguitk as simplegui
import time
#new ones
import pandas as pd
from xgboost import XGBRegressor
import os
#skyjo game classes and functions
from skyjo_functions4 import *
#own functions for machine learning
from ml_functions2 import *
#for plotting 
from matplotlib import pyplot as plt
from matplotlib.pyplot import figure

The different computer levels against each other. Testing the nwest level 5, first against the random level 0. 

In [21]:
#5 against 1 takes forever 

names=('alpha','beta')
nature=('computer','computer')
levels=(6,2)
start_time=time.time()
nn=int(1000)
all_scores=np.zeros((7,nn))
for i in range(nn):
    print(f"running case {i}")
    scores,turns,last_player,output=skyjo_round(names,nature,levels,0,True,True,True)
    all_scores[0,i]=i
    all_scores[1:3,i]=scores
    all_scores[3,i]=turns
    all_scores[4,i]=np.argmin(scores)
    all_scores[5,i]=output[0,0]
    all_scores[6,i]=output[0,output.shape[1]-1]    
stop_time=time.time()
print(f"running time was {stop_time-start_time}")
print(all_scores.T)
np.savetxt("level6_level2_1000_1.txt",all_scores)

running case 0
running case 1
running case 2
running case 3
running case 4
running case 5
running case 6
running case 7
running case 8
running case 9
running case 10
running case 11
running case 12
running case 13
running case 14
running case 15
running case 16
running case 17
running case 18
running case 19
running case 20
running case 21
running case 22
running case 23
running case 24
running case 25
running case 26
running case 27
running case 28
running case 29
running case 30
running case 31
running case 32
running case 33
running case 34
running case 35
running case 36
running case 37
running case 38
running case 39
running case 40
running case 41
running case 42
running case 43
running case 44
running case 45
running case 46
running case 47
running case 48
running case 49
running case 50
running case 51
running case 52
running case 53
running case 54
running case 55
running case 56
running case 57
running case 58
running case 59
running case 60
running case 61
running case 62
ru

running case 489
running case 490
running case 491
running case 492
running case 493
running case 494
running case 495
running case 496
running case 497
running case 498
running case 499
running case 500
running case 501
running case 502
running case 503
running case 504
running case 505
running case 506
running case 507
running case 508
running case 509
running case 510
running case 511
running case 512
running case 513
running case 514
running case 515
running case 516
running case 517
running case 518
running case 519
running case 520
running case 521
running case 522
running case 523
running case 524
running case 525
running case 526
running case 527
running case 528
running case 529
running case 530
running case 531
running case 532
running case 533
running case 534
running case 535
running case 536
running case 537
running case 538
running case 539
running case 540
running case 541
running case 542
running case 543
running case 544
running case 545
running case 546
running case 5

running case 971
running case 972
running case 973
running case 974
running case 975
running case 976
running case 977
running case 978
running case 979
running case 980
running case 981
running case 982
running case 983
running case 984
running case 985
running case 986
running case 987
running case 988
running case 989
running case 990
running case 991
running case 992
running case 993
running case 994
running case 995
running case 996
running case 997
running case 998
running case 999
running time was 1828.4805719852448
[[  0.  18.  45. ...   0.   1.   1.]
 [  1.  26.   7. ...   1.   1.   0.]
 [  2.  23.   7. ...   1.   0.   0.]
 ...
 [997.  48.  25. ...   1.   0.   0.]
 [998.  21.  28. ...   0.   1.   1.]
 [999.  19.   2. ...   1.   1.   0.]]


In [4]:
all_scores=np.loadtxt("level5_level0_1000_0.txt")
deltalevel5=0
deltalevel0=0
for i in range(all_scores.shape[1]):
    if all_scores[1,i]<all_scores[2,i]:
        #to calculate by how much a  human wins in average 
        deltalevel5+=(all_scores[2,i]-all_scores[1,i])
    else:
        deltalevel0+=(all_scores[1,i]-all_scores[2,i])
print("level 5 gainst level 0")
print(f"level 5 won {int(1000-sum(all_scores[4]))} times of {all_scores.shape[1]} rounds")
print(f"the level 5 average is {round(np.mean(all_scores[1]),3)} points")
print(f"the level 0 average is {round(np.mean(all_scores[2]),3)} points")
print(f"the level 5 average adventage is  {round(np.mean(all_scores[2]-all_scores[1]),3)} points")
print(f"level 5 wins to {round(np.mean(100-all_scores[4]*100),1)} %")
print(f"level 5 average adventage {round(deltalevel5/(1000-sum(all_scores[4])),3)} points")
print(f"level 0 average adventage {round(deltalevel0/(sum(all_scores[4])),3)} points")

level 5 gainst level 0
level 5 won 995 times of 1000 rounds
the level 5 average is 15.078 points
the level 0 average is 123.582 points
the level 5 average adventage is  108.504 points
level 5 wins to 99.5 %
level 5 average adventage 109.113 points
level 0 average adventage 12.6 points


Level 5 performs very well against level 0. That is expected since it is trained on it. Thus it mainly tested that there was no coding mistake. 

Now comparing it aginst the xgboost model tarine don the same original data but without feature engering. 
To both noise is added because when they are running against it each without noise it frequently gets into an inifite loop. 


In [26]:
all_scores1=np.loadtxt("level6_level2_1000_0.txt")
all_scores2=np.loadtxt("level6_level2_1000_1.txt")
all_scores=np.zeros((7,2000))
all_scores[:,0:1000]=all_scores1
all_scores[:,1000:2000]=all_scores2
print(f"to {np.round(np.mean(all_scores[6])*100,3)} % finishes level 2")
deltalevel6=0
deltalevel2=0
for i in range(all_scores.shape[1]):
    if all_scores[1,i]<all_scores[2,i]:
        #to calculate by how much a  human wins in average 
        deltalevel6+=(all_scores[2,i]-all_scores[1,i])
    else:
        deltalevel2+=(all_scores[1,i]-all_scores[2,i])
print("level 6 gainst level 2")
print(f"level 6 won {int(all_scores.shape[1]-sum(all_scores[4]))} times of {all_scores.shape[1]} rounds")
print(f"the level 6 average is {round(np.mean(all_scores[1]),3)} points")
print(f"the level 2 average is {round(np.mean(all_scores[2]),3)} points")
print(f"the level 6 average adventage is  {round(np.mean(all_scores[2]-all_scores[1]),3)} points")
print(f"level 6 wins to {round(np.mean(100-all_scores[4]*100),1)} %")
print(f"level 6 average adventage {round(deltalevel6/(all_scores.shape[1]-sum(all_scores[4])),3)} points")
print(f"level 2 average adventage {round(deltalevel2/(sum(all_scores[4])),3)} points")

to 46.2 % finishes level 2
level 6 gainst level 2
level 6 won 1056 times of 2000 rounds
the level 6 average is 19.429 points
the level 2 average is 22.916 points
the level 6 average adventage is  3.486 points
level 6 wins to 52.8 %
level 6 average adventage 20.605 points
level 2 average adventage 15.663 points


Level 6 is betetr, but not clear whether robsut against noise, but even if it is better it is a small not so relevant adventage.  

In [ ]:
Slowly playing against human, but seems that there is likely at most a small advantage. 