In [1]:
#should suppress warnings
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

import numpy as np
import random as random
import scipy
#using simpleguitk for display, is not needed for computer game
import simpleguitk as simplegui
import time
#new ones
import pandas as pd
from xgboost import XGBRegressor
import os
#skyjo game classes and functions
from skyjo_functions4 import *
#own functions for machine learning
from ml_functions2 import *
#for plotting 
from matplotlib import pyplot as plt
from matplotlib.pyplot import figure

The different computer levels against each other. Testing the newest level 9 and then 11, first against the random level 0. 

Then again level 5 which seems to be the best previous level (or level 1 but both are rather similar anyway). Since level 5 gets sometime sin an infinite loope, level 6 is used instead. 

In [20]:
 

names=('alpha','beta')
nature=('computer','computer')
levels=(15,0)
start_time=time.time()
nn=int(1000)
all_scores=np.zeros((7,nn))
for i in range(nn):
    print(f"running case {i}")
    scores,turns,last_player,output=skyjo_round(names,nature,levels,0,True,True,True)
    all_scores[0,i]=i
    all_scores[1:3,i]=scores
    all_scores[3,i]=turns
    all_scores[4,i]=np.argmin(scores)
    all_scores[5,i]=output[0,0]
    all_scores[6,i]=output[0,output.shape[1]-1]    
stop_time=time.time()
print(f"running time was {stop_time-start_time}")
print(all_scores.T)
np.savetxt("level15_level0_1000_0.txt",all_scores)

running case 0
running case 1
running case 2
running case 3
running case 4
running case 5
running case 6
running case 7
running case 8
running case 9
running case 10
running case 11
running case 12
running case 13
running case 14
running case 15
running case 16
running case 17
running case 18
running case 19
running case 20
running case 21
running case 22
running case 23
running case 24
running case 25
running case 26
running case 27
running case 28
running case 29
running case 30
running case 31
running case 32
running case 33
running case 34
running case 35
running case 36
running case 37
running case 38
running case 39
running case 40
running case 41
running case 42
running case 43
running case 44
running case 45
running case 46
running case 47
running case 48
running case 49
running case 50
running case 51
running case 52
running case 53
running case 54
running case 55
running case 56
running case 57
running case 58
running case 59
running case 60
running case 61
running case 62
ru

running case 490
running case 491
running case 492
running case 493
running case 494
running case 495
running case 496
running case 497
running case 498
running case 499
running case 500
running case 501
running case 502
running case 503
running case 504
running case 505
running case 506
running case 507
running case 508
running case 509
running case 510
running case 511
running case 512
running case 513
running case 514
running case 515
running case 516
running case 517
running case 518
running case 519
running case 520
running case 521
running case 522
running case 523
running case 524
running case 525
running case 526
running case 527
running case 528
running case 529
running case 530
running case 531
running case 532
running case 533
running case 534
running case 535
running case 536
running case 537
running case 538
running case 539
running case 540
running case 541
running case 542
running case 543
running case 544
running case 545
running case 546
running case 547
running case 5

running case 972
running case 973
running case 974
running case 975
running case 976
running case 977
running case 978
running case 979
running case 980
running case 981
running case 982
running case 983
running case 984
running case 985
running case 986
running case 987
running case 988
running case 989
running case 990
running case 991
running case 992
running case 993
running case 994
running case 995
running case 996
running case 997
running case 998
running case 999
running time was 185.13047242164612
[[  0.  14. 150. ...   0.   1.   0.]
 [  1.  43. 124. ...   0.   1.   0.]
 [  2.  16. 108. ...   0.   0.   0.]
 ...
 [997.  22.  76. ...   0.   0.   1.]
 [998.   9. 138. ...   0.   1.   0.]
 [999.  16.  70. ...   0.   1.   1.]]


In [49]:
def combine_results(list_inputs,level0=0,level1=2,silent=False,losses=True,rounds=True):
    cc=0
    for i in range(len(list_inputs)):
        a=np.loadtxt(list_inputs[i])
        cc+=a.shape[1]
    res=np.zeros((a.shape[0],int(cc))) 
    cc=0
    for i in range(len(list_inputs)):
        a=np.loadtxt(list_inputs[i])
        res[:,cc:cc+a.shape[1]]=a
        cc+=a.shape[1]    
    deltalevela=0
    deltalevelb=0
    for i in range(res.shape[1]):
        if res[1,i]<res[2,i]:
            #to calculate by how first and second plkayer win in average
            deltalevela+=(res[2,i]-res[1,i])
        else:
            deltalevelb+=(res[1,i]-res[2,i])
    if rounds==True:
        print(f"level {int(level0)} against level {int(level1)} in rounds")
        
    print(f"to {np.round(np.mean(res[6])*100,3)} % finishes level {int(level1)}")    
    if losses==True:
        print(f"level {int(level0)} lost {(res.shape[1]-int(res.shape[1]-sum(res[4])))} times of {res.shape[1]} rounds")
    else:
        print(f"level {int(level1)} won {int(res.shape[1]-sum(res[4]))} times of {all_scores.shape[1]} rounds")
    print(f"the level {int(level0)} average is {round(np.mean(res[1]),3)} points")
    print(f"the level {int(level1)} average is {round(np.mean(res[2]),3)} points")
    print(f"the level {int(level0)} average adventage is  {round(np.mean(res[2]-res[1]),3)} points")
    print(f"level {int(level0)} wins to {round(np.mean(100-res[4]*100),1)} %")
    print(f"level {int(level1)} average win adventage is {round(deltalevela/(res.shape[1]-sum(res[4])),3)} points")
    print(f"level {int(level0)} average win adventage is {round(deltalevelb/(sum(res[4])),3)} points") 
    print(" ")
    return res

In [50]:

level9level0=combine_results(["level9_level0_500_0.txt","level9_level0_1500_0.txt","level9_level0_3000_0.txt"],level0=9,level1=0)

level11level0=combine_results(["level11_level0_500_0.txt","level11_level0_1500_0.txt","level11_level0_3000_0.txt"],level0=11,level1=0)

level13level0=combine_results(["level13_level0_1000_0.txt","level13_level0_2500_0.txt","level13_level0_2000_0.txt"],level0=13,level1=0)

level15level0=combine_results(["level15_level0_1000_0.txt","level15_level0_2500_0.txt","level15_level0_2000_0.txt"],level0=15,level1=0)


level 9 against level 0 in rounds
to 59.54 % finishes level 0
level 9 lost 106 times of 5000 rounds
the level 9 average is 27.766 points
the level 0 average is 86.321 points
the level 9 average adventage is  58.556 points
level 9 wins to 97.9 %
level 0 average win adventage is 60.379 points
level 9 average win adventage is 25.613 points
 
level 11 against level 0 in rounds
to 65.88 % finishes level 0
level 11 lost 43 times of 5000 rounds
the level 11 average is 20.82 points
the level 0 average is 85.997 points
the level 11 average adventage is  65.177 points
level 11 wins to 99.1 %
level 0 average win adventage is 65.998 points
level 11 average win adventage is 29.465 points
 
level 13 against level 0 in rounds
to 81.182 % finishes level 0
level 13 lost 91 times of 5500 rounds
the level 13 average is 24.011 points
the level 0 average is 76.189 points
the level 13 average adventage is  52.178 points
level 13 wins to 98.3 %
level 0 average win adventage is 53.769 points
level 13 average 

Level 9 and level 11 performs very well against level 0. That is good and was not guranteed since it was trained mostly on rather few human data sets. 

Level 11 performs better with less than half the losses of level 9 as it should be since it is trained on winning in on imitating humans. 

Level 13 (human) and 15 (win) perform similar as their sibling above, thus there was no necessary an improvement compatred to 9 and 11 as was the aim at least for 15. 13 might be worse but that is human imitation. 





In [53]:
level9level6=combine_results(["level9_level6_500_0.txt","level9_level6_1500_0.txt","level9_level6_3000_0.txt"],level0=9,level1=6,losses=False)

level11level6=combine_results(["level11_level6_500_0.txt","level11_level6_1500_0.txt","level11_level6_3000_0.txt"],level0=11,level1=6,losses=False)

level13level6=combine_results(["level13_level6_500_0.txt","level13_level6_300_0.txt","level13_level6_4000_0.txt"],level0=13,level1=6,losses=False)

level15level6=combine_results(["level15_level6_500_0.txt","level15_level6_300_0.txt","level15_level6_4000_0.txt"],level0=15,level1=6,losses=False)


level 9 against level 6 in rounds
to 83.64 % finishes level 6
level 6 won 2193 times of 5000 rounds
the level 9 average is 35.35 points
the level 6 average is 22.024 points
the level 9 average adventage is  -13.326 points
level 9 wins to 43.9 %
level 6 average win adventage is 12.545 points
level 9 average win adventage is 33.538 points
 
level 11 against level 6 in rounds
to 87.62 % finishes level 6
level 6 won 2237 times of 5000 rounds
the level 11 average is 35.235 points
the level 6 average is 21.885 points
the level 11 average adventage is  -13.35 points
level 11 wins to 44.7 %
level 6 average win adventage is 12.761 points
level 11 average win adventage is 34.49 points
 
level 13 against level 6 in rounds
to 92.854 % finishes level 6
level 6 won 2038 times of 5000 rounds
the level 13 average is 41.668 points
the level 6 average is 22.568 points
the level 13 average adventage is  -19.1 points
level 13 wins to 42.5 %
level 6 average win adventage is 12.171 points
level 13 average w

The human imitation level (9) performs somehwhat worse than level 6, clearer in the points than in the win fraction. 

Level 11 performs very similar, slightly more wins but with worse losses. 

Level 13 (another trial of human imitation) and 15 (another trial of winning) perform also very similar and are thus not a successful improvement. 

Still the more important metric is compared to humans. 